config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  mount Ckeditor::Engine => '/ckeditor'
  resources :services

  devise_for :users

  resources :products, only: %i[index show], path: 'ads' do
    member do
      post :start_chat
    end
  end
  resources :chats, only: %i[index create show] do
    resources :messages, only: %i[create]
  end
  resources :categories, only: [:index, :show]
  resources :services, only: %i[index show]
  resources :blogs, only: %i[index show]
  resources :contacts, only: [:index]
  resources :abouts, only: [:index]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
  get "home/policy"
  get "home/terms"

  namespace :dashboard do
    resources :categories
    resources :paid_ads
    resources :products, path: 'my_ads' do
      collection do
        post :get_address
        get :filtered_categories
      end
    end
    get '/', to: 'dashboard#index'
  end

  namespace :admin do
    resources :sliders
    get '/', to: 'dashboard#index'
    resources :categories do
      member do
        patch :archive
        patch :unarchive
      end
    end
    resources :services
    resources :blogs
    resources :social_media_links
    resources :products, path: 'my_ads' do
      member do
        patch :approve
        patch :reject
      end
      collection do
        get :filtered_categories
      end
    end
    resources :paid_ads do
      member do
        patch :approve
        patch :reject
      end
    end
    resources :users
    resources :chats, only: [:index, :show]
  end

  resources :paid_ads do
    member do
      patch :approve
      patch :reject
    end
  end
end

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-glass">
  <div class="container-fluid">
    <div class="d-flex justify-content-between align-items-center w-100">
      <div class="d-flex align-items-center">
        <a class="text-inherit d-block d-xl-none me-4" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
          <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-text-indent-right" viewBox="0 0 16 16">
            <path
              d="M2 3.5a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5zm10.646 2.146a.5.5 0 0 1 .708.708L11.707 8l1.647 1.646a.5.5 0 0 1-.708.708l-2-2a.5.5 0 0 1 0-.708l2-2zM2 6.5a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5zm0 3a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5zm0 3a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5z" />
          </svg>
        </a>

      </div>
      <div>
        <ul class="list-unstyled d-flex align-items-center mb-0 ms-5 ms-lg-0">

          <li class="dropdown ms-4">
            <a href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <% if current_user.avatar.attached? %>
                <%= image_tag url_for(current_user.avatar), class: "avatar avatar-md rounded-circle" %>
              <% else %>
                <img src="<%= asset_path('theme/avatar/avatar-1.jpg') %>" alt="" class="avatar avatar-md rounded-circle" />
              <% end %>
            </a>

            <div class="dropdown-menu dropdown-menu-end p-0">
              <div class="lh-1 px-5 py-4 border-bottom">
                <h5 class="mb-1 h6"><%= current_user.name %></h5>
                <small><%=  current_user.email %></small>
              </div>

              <ul class="list-unstyled px-2 py-3">
                <li>
                  <a class="dropdown-item" href="<%= root_path %>">Home</a>
                </li>
                <li>
                  <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
                </li>
              </ul>
              <div class="border-top px-5 py-3">
                <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary d-none d-xl-block' %>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/admin/_mobile_nav_bar.html.erb
<nav class="navbar-vertical-nav offcanvas offcanvas-start navbar-offcanvac" tabindex="-1" id="offcanvasExample">
  <div class="navbar-vertical">
    <div class="px-4 py-5 d-flex justify-content-between align-items-center">
      <a href="<%= root_path %>" class="navbar-brand">
        <img src="/assets/logo-large.png" alt="" />
      </a>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="navbar-vertical-content flex-grow-1" data-simplebar="">
      <ul class="navbar-nav flex-column">
        <li class="nav-item">
          <a class="nav-link active" href="<%= admin_path %>">
            <div class="d-flex align-items-center">
              <span class="nav-link-icon"><i class="bi bi-house"></i></span>
              <span>Dashboard</span>
            </div>
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link <%= active_tab('products').present? ? 'collapse parent-active' : '' %>" href="#" data-bs-toggle="collapse" data-bs-target="#navCategoriesOrders" aria-expanded="false" aria-controls="navCategoriesOrders">
            <div class="d-flex align-items-center">
              <span class="nav-link-icon"><i class="bi bi-bag"></i></span>
              <span class="nav-link-text">Ads</span>
            </div>
          </a>
          <div id="navCategoriesOrders" class="collapse  <%= " show" if active_tab('products').present? %>" data-bs-parent="#sideNavbar">
            <ul class="nav flex-column">
              <li class="nav-item">
                <%= link_to admin_products_path, class: "nav-link  #{active_tab_with_tabs('products', 'all')}" do %>
                  <span class="nav-link-text">All Ads</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_products_path(status: 'draft'), class: "nav-link #{active_tab_with_tabs("products", 'draft')}" do %>
                  <span class="nav-link-text">Draft</span>
                <% end %>
              </li>
              <!-- Nav item -->
              <li class="nav-item">
                <%= link_to admin_products_path(status: 'pending'), class: "nav-link #{active_tab_with_tabs("products", 'pending')}" do %>
                  <span class="nav-link-text">Pending</span>
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to admin_products_path(status: 'approved'), class: "nav-link #{active_tab_with_tabs("products", 'approved')}" do %>
                  <span class="nav-link-text">Approved</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_products_path(status: 'rejected'), class: "nav-link #{active_tab_with_tabs("products", 'rejected')}" do %>
                  <span class="nav-link-text">Rejected</span>
                <% end %>
              </li>
            </ul>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to admin_paid_ads_path, class: "nav-link #{active_tab('paid_ads')}" do %>
            <div class="d-flex align-items-center">
              <span class="nav-link-icon"><i class="bi bi-list-task"></i></span>
              <span class="nav-link-text">Paid Ads Requests</span>
            </div>
          <% end %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= admin_categories_path %>">
            <div class="d-flex align-items-center">
              <span class="nav-link-icon"><i class="bi bi-list-task"></i></span>
              <span class="nav-link-text">Categories</span>
            </div>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= admin_services_path %>">
            <div class="d-flex align-items-center">
              <span class="nav-link-icon"><i class="bi bi-list-task"></i></span>
              <span class="nav-link-text">Services</span>
            </div>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= admin_blogs_path %>">
            <div class="d-flex align-items-center">
              <span class="nav-link-icon"><i class="bi bi-list-task"></i></span>
              <span class="nav-link-text">Blogs</span>
            </div>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= admin_social_media_links_path %>">
            <div class="d-flex align-items-center">
              <span class="nav-link-icon"><i class="bi bi-share"></i></span>
              <span class="nav-link-text">Social Media Links</span>
            </div>
          </a>
        </li>
        <li class="nav-item">
          <%= link_to admin_sliders_path, class: "nav-link #{active_tab('sliders')}" do %>
            <div class="d-flex align-items-center">
              <span class="nav-link-icon"><i class="bi bi-images"></i></span>
              <span class="nav-link-text">Sliders</span>
            </div>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to admin_users_path, class: "nav-link #{active_tab('users')}" do %>
            <div class="d-flex align-items-center">
              <span class="nav-link-icon"><i class="bi bi-list-task"></i></span>
              <span class="nav-link-text">users</span>
            </div>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to admin_chats_path, class: "nav-link #{active_tab('chats')}" do %>
            <div class="d-flex align-items-center">
              <span class="nav-link-icon"><i class="bi bi-list-task"></i></span>
              <span class="nav-link-text">chats</span>
            </div>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin/_sidebar.html.erb
<nav class="navbar-vertical-nav d-none d-xl-block">
  <div class="navbar-vertical">
    <div class="px-4 py-5">
      <a href="<%= root_path %>" class="navbar-brand">
        <img src="<%= asset_path('logo-large.png') %>" alt="" />
      </a>
    </div>
    <div class="navbar-vertical-content flex-grow-1" data-simplebar="">
      <ul class="navbar-nav flex-column" id="sideNavbar">

        <li class="nav-item">
          <%= link_to admin_path, class: "nav-link #{active_tab('dashboard')}" do %>
            <div class="d-flex align-items-center">
              <span class="nav-link-icon"><i class="bi bi-house"></i></span>
              <span class="nav-link-text">Dashboard</span>
            </div>
          <% end %>
        </li>
        <li class="nav-item">
          <a class="nav-link <%= active_tab('products').present? ? 'collapse parent-active' : '' %>" href="#" data-bs-toggle="collapse" data-bs-target="#navCategoriesOrders" aria-expanded="false" aria-controls="navCategoriesOrders">
            <div class="d-flex align-items-center">
              <span class="nav-link-icon"><i class="bi bi-bag"></i></span>
              <span class="nav-link-text">Ads</span>
            </div>
          </a>
          <div id="navCategoriesOrders" class="collapse  <%= " show" if active_tab('products').present? %>" data-bs-parent="#sideNavbar">
            <ul class="nav flex-column">
              <li class="nav-item">
                <%= link_to admin_products_path, class: "nav-link  #{active_tab_with_tabs('products', 'all')}" do %>
                  <span class="nav-link-text">All Ads</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_products_path(status: 'draft'), class: "nav-link #{active_tab_with_tabs("products", 'draft')}" do %>
                  <span class="nav-link-text">Draft</span>
                <% end %>
              </li>
              <!-- Nav item -->
              <li class="nav-item">
                <%= link_to admin_products_path(status: 'pending'), class: "nav-link #{active_tab_with_tabs("products", 'pending')}" do %>
                  <span class="nav-link-text">Pending</span>
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to admin_products_path(status: 'approved'), class: "nav-link #{active_tab_with_tabs("products", 'approved')}" do %>
                  <span class="nav-link-text">Approved</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_products_path(status: 'rejected'), class: "nav-link #{active_tab_with_tabs("products", 'rejected')}" do %>
                  <span class="nav-link-text">Rejected</span>
                <% end %>
              </li>
            </ul>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to admin_paid_ads_path, class: "nav-link #{active_tab('paid_ads')}" do %>
            <div class="d-flex align-items-center">
              <span class="nav-link-icon"><i class="bi bi-list-task"></i></span>
              <span class="nav-link-text">Paid Ads Requests</span>
            </div>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to admin_categories_path, class: "nav-link #{active_tab('categories')}" do %>
            <div class="d-flex align-items-center">
              <span class="nav-link-icon"><i class="bi bi-list-task"></i></span>
              <span class="nav-link-text">Categories</span>
            </div>
          <% end %>
        </li>

        <li class="nav-item">
          <%= link_to admin_services_path, class: "nav-link #{active_tab('services')}" do %>
            <div class="d-flex align-items-center">
              <span class="nav-link-icon"><i class="bi bi-list-task"></i></span>
              <span class="nav-link-text">Services</span>
            </div>
          <% end %>
        </li>

        <li class="nav-item">
          <%= link_to admin_blogs_path, class: "nav-link #{active_tab('blogs')}" do %>
            <div class="d-flex align-items-center">
              <span class="nav-link-icon"><i class="bi bi-list-task"></i></span>
              <span class="nav-link-text">Blogs</span>
            </div>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to admin_social_media_links_path, class: "nav-link #{active_tab('social_media_links')}" do %>
            <div class="d-flex align-items-center">
              <span class="nav-link-icon"><i class="bi bi-share"></i></span>
              <span class="nav-link-text">Social Media Links</span>
            </div>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to admin_sliders_path, class: "nav-link #{active_tab('sliders')}" do %>
            <div class="d-flex align-items-center">
              <span class="nav-link-icon"><i class="bi bi-images"></i></span>
              <span class="nav-link-text">Sliders</span>
            </div>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to admin_users_path, class: "nav-link #{active_tab('users')}" do %>
            <div class="d-flex align-items-center">
              <span class="nav-link-icon"><i class="bi bi-list-task"></i></span>
              <span class="nav-link-text">users</span>
            </div>
          <% end %>
        </li>
                <li class="nav-item">
          <%= link_to admin_chats_path, class: "nav-link #{active_tab('chats')}" do %>
            <div class="d-flex align-items-center">
              <span class="nav-link-icon"><i class="bi bi-list-task"></i></span>
              <span class="nav-link-text">chats</span>
            </div>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>