config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  mount Ckeditor::Engine => '/ckeditor'
  resources :services

  devise_for :users

  resources :products, only: %i[index show], path: 'ads' do
    member do
      post :start_chat
    end
  end
  resources :chats, only: %i[index create show] do
    resources :messages, only: %i[create]
  end
  resources :categories, only: [:index, :show]
  resources :services, only: %i[index show]
  resources :blogs, only: %i[index show]
  resources :contacts, only: [:index]
  resources :abouts, only: [:index]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
  get "home/policy"
  get "home/terms"

  namespace :dashboard do
    resources :categories
    resources :paid_ads
    resources :products, path: 'my_ads' do
      collection do
        post :get_address
        get :filtered_categories
      end
    end
    get '/', to: 'dashboard#index'
  end

  namespace :admin do
    resources :sliders
    get '/', to: 'dashboard#index'
    resources :categories do
      member do
        patch :archive
        patch :unarchive
      end
    end
    resources :services
    resources :blogs
    resources :social_media_links
    resources :products, path: 'my_ads' do
      member do
        patch :approve
        patch :reject
      end
      collection do
        get :filtered_categories
      end
    end
    resources :paid_ads do
      member do
        patch :approve
        patch :reject
      end
    end
    resources :users
    resources :chats, only: [:index, :show]
  end

  resources :paid_ads do
    member do
      patch :approve
      patch :reject
    end
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Admin::BaseController
    before_action :set_product, only: %i[ show edit update destroy approve reject ]

    def index
      @products = Product.all
      
      if params[:status].present?
        @products = @products.where(status: params[:status])
      end

      if params[:search].present?
        @products = @products.where("name ILIKE ?", "%#{params[:search]}%")
      end
      
      @products = @products.page(params[:page])

      respond_to do |format|
        format.html
        format.json do
          render json: {
            html: render_to_string(partial: 'product_rows', locals: { products: @products }, formats: [:html])
          }
        end
      end
    end

    def show; end

    def new
      @product = current_user.products.new
    end

    def edit; end

    def create
      @product = current_user.products.new(product_params)

      if @product.save
        redirect_to admin_products_path, notice: "Product was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @product.update(product_params.reject { |k| k["images"] })
        if product_params[:images].present?
          product_params[:images].each do |image|
            @product.images.attach(image)
          end
        end

        redirect_to admin_products_path, notice: "Product was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @product.destroy!
      redirect_to admin_products_path, notice: "Product was successfully destroyed."
    end

    def approve
      if @product.update(status: 'approved', verified: true)
        # Send approval notification email
        ProductMailer.approval_notification(@product).deliver_later
        redirect_to admin_product_path(@product), notice: "Product was successfully approved and notification email has been sent."
      else
        redirect_to admin_product_path(@product), alert: "Failed to approve product."
      end
    end

    def reject
      if @product.update(status: 'rejected')
        # Send rejection notification email
        @product.user.increment!(:number_of_ads)
        ProductMailer.rejection_notification(@product).deliver_later
        redirect_to admin_product_path(@product), notice: "Product was successfully rejected and notification email has been sent."
      else
        redirect_to admin_product_path(@product), alert: "Failed to reject product."
      end
    end

    def filtered_categories
      @categories = Category.find_by(id: params[:parent_category_id]).sub_categories
      render json: @categories.map { |c| [c.name, c.id] }
    end

    private
      def set_product
        @product = Product.find(params[:id])
      end

      def product_params
        params.require(:product).permit(:user_id, :category_id, :status, :name, :short_description, :long_description, :age, :sex, :breed, :height, :weight, :teeth, :castrated, :price, :quantity, :city, :country, :state, :address, :self_stock, :verified, :quantity_unit, :primary_image, :pregnant, :daily_milk_quantity, images: [])
      end
  end
end

app/controllers/dashboard/base_controller.rb
class Dashboard:: BaseController < ApplicationController
  before_action :authenticate_user!

  layout 'dashboard'
  # Controller actions
end

app/controllers/dashboard/categories_controller.rb
class Dashboard::CategoriesController < Dashboard::BaseController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to dashboard_categories_path, notice: "category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to dashboard_categories_path, notice: "category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description, :image)
    end
end

app/controllers/dashboard/dashboard_controller.rb
class Dashboard::DashboardController < Dashboard::BaseController
  def index
  end
end

app/controllers/dashboard/paid_ads_controller.rb
class Dashboard::PaidAdsController < Dashboard::BaseController
  before_action :set_paid_ad, only: %i[ show edit update destroy ]

  # GET /paid_ads
  def index
    @paid_ads = current_user.paid_ads.page(page).per(per)
  end

  # GET /paid_ads/1 or /paid_ads/1.json
  def show
  end

  # GET /paid_ads/new
  def new
    @paid_ad = PaidAd.new
  end

  # GET /paid_ads/1/edit
  def edit; end

  # POST /paid_ads or /paid_ads.json
  def create
    @paid_ad = current_user.paid_ads.new(paid_ad_params)

      if @paid_ad.save
        redirect_to dashboard_paid_ads_path, notice: "Paid ad was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
  end

  # PATCH/PUT /paid_ads/1 or /paid_ads/1.json
  def update
    if @paid_ad.update(paid_ad_params)
      redirect_to dashboard_paid_ads_path, notice: "Paid ad was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /paid_ads/1 or /paid_ads/1.json
  def destroy
    @paid_ad.destroy!

    respond_to do |format|
      format.html { redirect_to dashboard_paid_ads_url, notice: "Paid ad was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paid_ad
      @paid_ad = current_user.paid_ads.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def paid_ad_params
      params.require(:paid_ad).permit(:user_id, :quantity, :status, :ad_type, :payment_method, :proof_image)
    end
end

app/controllers/dashboard/products_controller.rb
module Dashboard
  class ProductsController < Dashboard::BaseController
    before_action :set_product, only: %i[ show edit update destroy ]

    def index
      if params[:search].present?
        @products = current_user.products.filter_by_status(params[:type]).search_by_name(params[:search]).page(page).per(per)
      else
        @products = current_user.products.filter_by_status(params[:type]).page(page).per(per)
      end
    end

    def show; end

    def new
      @product = current_user.products.new
    end

    def edit; end

    def create
      @product = current_user.products.new(product_params)

      if @product.save
        redirect_to dashboard_products_path, notice: "Product was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @product.update(product_params)
        redirect_to dashboard_products_path, notice: "Product was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @product.destroy!
      redirect_to dashboard_products_path, notice: "Product was successfully destroyed."
    end

    def get_address
      results = Geocoder.search([params[:lat], params[:long]])

      if results.present? && (result = results.first)
        address = result.address
        state = result.state
        city = result.city
        country = result.country

        if result.data.present? && (address_data = result.data["address"])
          city = (address_data["district"] || address_data["subdistrict"])&.gsub(/\bDistrict\b/, "")&.strip || city
          state = address_data["state"] || state
        end

        address_data = { address: address, city: city, state: state, country: country }
        render json: address_data
      else
        render json: { error: "Address information not found" }, status: :not_found
      end
    end

    def filtered_categories
      @categories = Category.find_by(id: params[:parent_category_id]).sub_categories
      render json: @categories.map { |c| [c.name, c.id] }
    end

    private
      def set_product
        @product = current_user.products.find(params[:id])
      end

      def product_params
        params.require(:product).permit(:user_id, :category_id, :status, :name, :short_description, :long_description, :age, :sex, :breed, :height, :weight, :teeth, :castrated, :price, :quantity, :city, :country, :state, :address, :self_stock, :verified, :quantity_unit, :primary_image, :pregnant, :daily_milk_quantity, images: [])
      end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show start_chat]

  # GET /products or /products.json
  def index
    @products = Product.approved
                       .joins(:category)
                       .merge(Category.unarchived)
                       .filter_by_query(params[:q])
                       .filter_by_category(params[:category_id])
                       .filter_by_self_stock(params[:self_stock])
                       .filter_by_price(params[:start_price], params[:end_price])
                       .filter_by_city(params[:city])
                       .then { |products| apply_sorting(products) }
                       .page(params[:page])
                       .per(params[:per_page] || 20)
    @categories = Category.parent_categories.unarchived
  end

  # GET /products/1 or /products/1.json
  def show
    @product.increment_view_count
    @related_products = @product.category.products.page(page).per(5)
  end

  def start_chat
    @chat = Chat.find_by(buyer: current_user, product: @product)
    unless @chat
      @chat = Chat.create!(buyer: current_user, seller: @product.user, product: @product)
    end
    redirect_to chats_path(@chat)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def apply_sorting(products)
      case params[:sort]
      when 'price_asc'
        products.reorder(price: :asc)
      when 'price_desc'
        products.reorder(price: :desc)
      when 'created_at'
        products.reorder(created_at: :desc)
      else
        products.reorder(created_at: :desc)
      end
    end
end

app/controllers/users/products_controller.rb
module Users
  class ProductsController < Users::BaseController
    before_action :set_product, only: %i[ show edit update destroy ]

    def index
      @products = current_user.products
    end

    def show; end

    def new
      @product = current_user.products.new
    end

    def edit; end

    def create
      @product = current_user.products.new(product_params)

      if @product.save
        redirect_to users_products_path, notice: "Product was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @product.update(product_params)
        redirect_to users_products_path, notice: "Product was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @product.destroy!
      redirect_to users_products_path, notice: "Product was successfully destroyed."
    end

    private
      def set_product
        @product = current_user.products.find(params[:id])
      end

      def product_params
        params.require(:product).permit(:user_id, :category_id, :status, :name, :short_description, :long_description, :age_in_years, :age_in_months, :sex, :breed, :height, :wight, :teeth, :castrated, :price, :quantity, :city, :countary, :state, :address, :self_stock, :verified, :quantity_unit)
      end
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
  def active_tab(curr_tab)
    "active" if controller.controller_name.downcase == curr_tab.downcase
  end

  def active_tab_with_tabs(curr_tab, tabs)
    "active"  if (controller.controller_name.downcase == curr_tab.downcase) && (params[:status]&.downcase == tabs.downcase || params[:type]&.downcase == tabs.downcase)    
  end

  def dynamic_breadcrum_path
    send("admin_#{controller_name}_path") rescue nil
  end
end

app/helpers/products_helper.rb
module ProductsHelper
    def image_url(source)
        image_path(URI.join(root_url, url_for(source)))
      end
end

app/helpers/users/dashboard_helper.rb
module Users::DashboardHelper
end

app/views/dashboard/products/_form.html.erb
<div class="container">
<%= render partial: "/dashboard/shared/breadcrum" %>

    <div class="row">
      <div class="col-lg-10 col-12">
        <div class="card mb-10 card-lg">
          <div class="card-body p-6">
            <h4 class="mb-4 h5">Ad Details</h4>
            <%= form_with(model: [:dashboard, product]) do |form| %>
              <% if product.errors.any? %>
                <div style="color: red">
                  <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
                  <ul>
                    <% product.errors.each do |error| %>
                      <li><%= error.full_message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
              <div class="row" data-controller="category-form dairy-fields">
                <div class="mb-3 col-lg-6">
                  <%= form.label :parent_id, "Category", class: "form-label" %>
                  <%= form.select :parent_id, Category.where(parent_id: nil).pluck(:name, :id), { include_blank: "Select Category", selected: product.category&.parent_id }, { class: "form-select", data: { category_form_target: "parentCategory" } } %>
                </div>

                <div class="mb-3 col-lg-6">
                  <%= form.label :category_id, "Sub Category", class: "form-label" %>
                  <%= form.select :category_id, product.category&.parent ? Category.where(parent_id: product.category.parent_id).pluck(:name, :id) : [], { include_blank: "Select Sub Category" }, { class: "form-select", data: { category_form_target: "childCategory", dairy_fields_target: "categorySelector" } } %>
                </div>
                <div class="mb-3 col-lg-6">
                  <%= form.label "Ad Name", class: "form-label" %>
                  <%= form.text_field :name, class: "form-control" %>
                </div>
                <div class="mb-3 col-lg-6">
                  <%= form.label :quantity, class: "form-label" %>
                  <%= form.number_field :quantity, class: "form-control" %>
                </div>
                <div class="mb-3 col-lg-6">
                  <%= form.label :quantity_unit, class: "form-label" %>
                  <%= form.select :quantity_unit, Product.quantity_units.keys.map { |unit| [unit.humanize, unit] }, { include_blank: "Select Quantity Unit" }, class: "form-select" %>
                </div>

                <div class="mb-3 col-lg-6">
                  <%= form.label :sex, "Gender", class: "form-label" %>
                  <%= form.select :sex, Product.sexes.keys.map { |sex| [sex.humanize, sex] }, { include_blank: "Select Gender" }, class: "form-select" %>
                </div>
                <div class="mb-3 col-lg-6">
                  <%= form.label :age, class: "form-label" %>
                  <%= form.number_field :age, class: "form-control", step: "0.1" %>
                </div>
                <div class="mb-3 col-lg-6">
                  <%= form.label :price, class: "form-label" %>
                  <div class="input-group">
                    <%= form.number_field :price, class: "form-control" %>
                    <span class="input-group-text">PKR</span>
                  </div>
                </div>

                <div class="mb-3 col-lg-6">
                  <%= form.label :breed, class: "form-label" %>
                  <%= form.text_field :breed, class: "form-control" %>
                </div>
                <div class="mb-3 col-lg-6">
                  <%= form.label :height, class: "form-label" %>
                   <div class="input-group">
                    <%= form.text_field :height, class: "form-control" %>
                    <span class="input-group-text">cm</span>
                  </div>
                </div>
                <div class="mb-3 col-lg-6">
                  <%= form.label :weight, class: "form-label" %>
                  <div class="input-group">
                    <%= form.text_field :weight, class: "form-control" %>
                    <span class="input-group-text">kg</span>
                  </div>
                </div>
                <div class="mb-3 col-lg-6">
                  <%= form.label :teeth, class: "form-label" %>
                  <%= form.number_field :teeth, class: "form-control" %>
                </div>
                <div class="mb-3 col-lg-6">
                  <div class="form-check mt-4">
                    <%= form.check_box :castrated, class: "form-check-input" %>
                    <%= form.label :castrated, class: "form-check-label" %>
                  </div>
                </div>

                <!-- Dairy animal fields - hidden by default -->
                <div id="dairy_fields" class="row" data-dairy-fields-target="dairyFields" style="display: none;">
                  <div class="mb-3 col-lg-6">
                    <%= form.label :pregnant, "Pregnant", class: "form-label" %>
                    <%= form.select :pregnant, [["Yes", true], ["No", false]], { include_blank: "Select" }, { class: "form-select" } %>
                  </div>
                  <div class="mb-3 col-lg-6">
                    <%= form.label :daily_milk_quantity, "Daily Milk Quantity (liters)", class: "form-label" %>
                    <%= form.number_field :daily_milk_quantity, step: 0.1, class: "form-control" %>
                  </div>
                </div>

                <div class="mb-3">
                  <h4 class="mb-3 h5">Location</h4>
                </div>
                <div data-controller='geolocation'>
                  <button data-action="geolocation#search" data-geolocation-target="button" class="btn btn-primary mb-2">
                    <span data-geolocation-target="buttonText">Get Current Location</span>
                  </button>
                  <div class="mb-3 col-lg-6">
                    <%= form.label :city, class: "form-label" %>
                    <%= form.text_field :city, class: "form-control", "data-geolocation-target": "city" %>
                  </div>

                  <div class="mb-3 col-lg-6">
                    <%= form.label :state, class: "form-label" %>
                    <%= form.text_field :state, class: "form-control", "data-geolocation-target": "state" %>
                  </div>

                  <div class="mb-3 col-lg-6">
                    <%= form.label :country, class: "form-label" %>
                    <%= form.text_field :country, class: "form-control", "data-geolocation-target": "country" %>
                  </div>
                  <div class="mb-3 col-lg-12">
                    <%= form.label :address, class: "form-label" %>
                    <%= form.text_area :address, class: "form-control", "data-geolocation-target": "address" %>
                  </div>
                </div>
                <div class="mb-3 col-lg-12 mt-5">
                  <h4 class="mb-3 h5">Primary Image</h4>
                  <div id="dash_prime_image_preview" class="image-preview-container">
                    <% if product.primary_image.attached? %>
                      <%= image_tag product.primary_image, class: "img-thumbnail", style: "max-width: 200px" %>
                    <% end %>
                  </div>
                  <div class="mb-3 col-lg-12">
                    <%= form.label :primary_image, class: "form-label", required: true %>
                    <%= form.file_field :primary_image, class: "form-control image-preview-input", data: { preview_target: '#dash_prime_image_preview' } %>
                  </div>
                </div>

                <div class="mb-3 col-lg-12 mt-5">
                  <h4 class="mb-3 h5">Product Images</h4>
                  <div id="dash_product_images_preview" class="image-preview-container">
                    <% if product.images.attached? %>
                      <% product.images.each do |image| %>
                        <%= image_tag image, class: "img-thumbnail me-2 mb-2", style: "max-width: 200px" %>
                      <% end %>
                    <% end %>
                  </div>
                  <div class="mb-6 col-lg-12">
                    <%= form.label :images, class: "form-label" %>
                    <%= form.file_field :images, multiple: true, class: "form-control image-preview-input", data: { preview_target: '#dash_product_images_preview' } %>
                  </div>
                </div>
              
              <div class="mb-12 col-lg-12">
                <%= form.label :short_description, class: "form-label" %>
                <%= form.text_field :short_description, class: "form-control" %>
              </div>

              <div class="mb-12 col-lg-12">
                <%= form.label :long_description, class: "form-label" %>
                <%= form.text_area :long_description, class: "form-control" %>
              </div>

              <div class="mb-3 d-flex justify-content-between align-items-center">
                <% if product.new_record? %>
                  <%= form.submit "Create Ad", class: "btn btn-primary"  %>
                <% else %>
                  <%= form.submit "Update Ad", class: "btn btn-primary"  %>
                <% end %>
                <%= link_to "Back to ads", products_path, class: "btn btn-light" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/dashboard/products/edit.html.erb
<%= render "form", product: @product %>

app/views/dashboard/products/index.html.erb
<div class="container">
  <%= render partial: "/dashboard/shared/breadcrum" %>
  <!-- row -->
  <div class="row">
    <div class="col-xl-12 col-12 mb-5">
      <!-- card -->
      <div class="card h-100 card-lg">
        <div class="px-6 py-6">
          <div class="row justify-content-between">
            <!-- form -->
            <div class="col-lg-4 col-md-6 col-12 mb-2 mb-lg-0">
              <form class="d-flex" role="search">
                <input class="form-control" name="search" type="search" placeholder="Search Ads" aria-label="Search" value="<%= params[:search] %>" />
              </form>
            </div>
          </div>
        </div>
        <!-- card body -->
        <div class="card-body p-0">
          <!-- table -->
          <div class="table-responsive">
            <table class="table table-centered table-hover text-nowrap table-borderless mb-0 table-with-checkbox">
              <thead class="bg-light">
              <tr>
                <th>Ad Name</th>
                <th>Category</th>
                <th>Status</th>
                <th>Price</th>
                <th>Views</th>
                <th>Hight</th>
                <th>Weight</th>
                <th>Breed</th>
                <th>Verified</th>
                <th>Quantity</th>
                <th>Image</th>
                <th>Actions</th>
              </tr>
              </thead>
              <tbody>
              <% @products.each do |product| %>
                <tr>
                  <td><a href="#" class="text-reset"><%= product.name %></a></td>
                  <td><%= product.category.name %></td>

                  <td>
                    <span class="badge <%= product.status == 'pending' ? 'bg-warning' : product.status == 'approved' ? 'bg-success' : 'bg-danger' %> text-light-primary"><%= product.status.titleize %></span>
                  </td>
                  <td><%= product.price %></td>
                  <td><%= product.view_count %></td>
                  <td><%= product.height %></td>
                  <td><%= product.weight %></td>
                  <td><%= product.breed %></td>
                  <td><%= product.verified %></td>
                  <td><%= product.quantity %></td>
                  <td>
                    <a href="#!">
                      <%= image_tag url_for(product.watermarked_primary_image), alt: product.short_description, class: 'icon-shape icon-md' if product.images.attached? %>
                    </a>
                  </td>
                  <td class="d-flex gap-2 justify-content-end">
                    <% if product.draft? || product.pending? %>
                      <%= link_to edit_dashboard_product_path(product),class: "btn btn-primary" do %>
                        Edit
                      <% end %>
                      <%= form_with url: dashboard_product_path(product), method: :delete, data: { confirm: "Are you sure?" } do %>
                        <%= submit_tag "Delete", class: "btn btn-danger" %>
                      <% end %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
        <%= paginate @products %>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/products/new.html.erb
<%= render "form", product: @product %>

app/views/dashboard/products/show.html.erb
<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
  <div class="bg-white shadow overflow-hidden sm:rounded-lg">
    <div class="px-4 py-5 sm:px-6 flex justify-between items-center">
      <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:truncate">
        <%= @product.name %>
      </h2>
      <div class="flex items-center space-x-4">
        <% if @product.user == current_user %>
          <%= link_to edit_users_product_path(@product), class: "inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" do %>
            <svg class="-ml-1 mr-2 h-5 w-5 text-gray-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
              <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
            </svg>
            Edit
          <% end %>
        <% end %>
        <%= link_to dashboard_products_path, class: "inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" do %>
          <svg class="-ml-1 mr-2 h-5 w-5 text-gray-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clip-rule="evenodd" />
          </svg>
          Back
        <% end %>
      </div>
    </div>

    <%= render @product %>

    <% if @product.user == current_user %>
      <div class="px-4 py-3 bg-gray-50 text-right sm:px-6 border-t border-gray-200">
        <%= button_to users_product_path, method: :delete, class: "inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500", data: { confirm: "Are you sure you want to delete this ad?" } do %>
          <svg class="-ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
          </svg>
          Delete Ad
        <% end %>
      </div>
    <% end %>
  </div>
</div>