config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  mount Ckeditor::Engine => '/ckeditor'
  resources :services

  devise_for :users

  resources :products, only: %i[index show], path: 'ads' do
    member do
      post :start_chat
    end
  end
  resources :chats, only: %i[index create show] do
    resources :messages, only: %i[create]
  end
  resources :categories, only: [:index, :show]
  resources :services, only: %i[index show]
  resources :blogs, only: %i[index show]
  resources :contacts, only: [:index]
  resources :abouts, only: [:index]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
  get "home/policy"
  get "home/terms"

  namespace :dashboard do
    resources :categories
    resources :paid_ads
    resources :products, path: 'my_ads' do
      collection do
        post :get_address
        get :filtered_categories
      end
    end
    get '/', to: 'dashboard#index'
  end

  namespace :admin do
    resources :sliders
    get '/', to: 'dashboard#index'
    resources :categories do
      member do
        patch :archive
        patch :unarchive
      end
    end
    resources :services
    resources :blogs
    resources :social_media_links
    resources :products, path: 'my_ads' do
      member do
        patch :approve
        patch :reject
      end
      collection do
        get :filtered_categories
      end
    end
    resources :paid_ads do
      member do
        patch :approve
        patch :reject
      end
    end
    resources :users
    resources :chats, only: [:index, :show]
  end

  resources :paid_ads do
    member do
      patch :approve
      patch :reject
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @categories = Category.unarchived.where(parent: nil)
        # update with popular scope
        @popular_products = Product.approved
                                 .joins(:category)
                                 .merge(Category.unarchived)
                                 .page(page)
                                 .per(per)
        @recent_products = Product.approved
                                .joins(:category)
                                .merge(Category.unarchived)
                                .page(page)
                                .per(per)
        @published_services = Service.published.page(page).per(per)
        @blogs = Blog.published.order("RANDOM()").page.per(per(3))
    end

    def policy

    end

    def terms

    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/shared/_best_selling_products.html.erb
<section class="my-lg-14">
  <div class="container">
    <!-- row -->
    <div class="row align-items-center mb-6">
      <div class="col-lg-10 col-10">
        <!-- heading -->
        <h3 class="align-items-center d-flex mb-0 h4">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="feather feather-shopping-bag text-primary">
              <path d="M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z"></path>
              <line x1="3" y1="6" x2="21" y2="6"></line>
              <path d="M16 10a4 4 0 0 1-8 0"></path>
            </svg>
          <h4 >Best Selling Ads</h4>
          <p class="mb-0">Find the bestseller ads in your area with discount.</p>
        </h3>
      </div>
      <div class="col-lg-2 col-2">
        <div class="slider-arrow" id="slider-fifth-arrows"></div>
      </div>
    </div>
    <!-- slider -->
    <div class="product-slider-second" id="slider-fifth">
      <!-- item -->
      <% @recent_products.each do |product| %>
        <div class="item">
          <!-- item -->
          <div class="card card-product mb-lg-4">
            <div class="card-body">
              <div class="text-center position-relative">

                <!--                 <a href="#!"><img src="/assets/theme/products/product-img-18.jpg" alt="Grocery Ecommerce Template" class="mb-3 img-fluid" /></a>-->

                <%= link_to product_path(product) do %>
                  <div class="product-img-container">
                    <% if product.primary_image.attached? %>
                      <%= image_tag url_for(product.watermarked_primary_image), alt: product.short_description %>
                    <% else %>
                      <%= image_tag 'theme/png/no-image.png', alt: product.short_description %>
                    <% end %>
                  </div>
                <% end %>
              </div>
              <!-- title -->
              <div class="text-small mb-1">
                <a href="#!" class="text-decoration-none text-muted"><small><%= product.category_name %></small></a>
              </div>
              <h2 class="fs-6">
                <%= link_to product.name, product_path(product), class: 'text-inherit text-decoration-none' %>
              </h2>
              <div class="text-warning">
                <!-- rating -->
                <small>
                  <i class="bi bi-star-fill"></i>
                  <i class="bi bi-star-fill"></i>
                  <i class="bi bi-star-fill"></i>
                  <i class="bi bi-star-half"></i>
                  <i class="bi bi-star"></i>
                </small>
                <span class="text-muted small">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-eye">
                    <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                    <circle cx="12" cy="12" r="3"></circle>
                  </svg>
                  <%= product.view_count || 0 %>
                </span>
              </div>
              <!-- price -->
              <div class="d-flex justify-content-between align-items-center mt-3">
                <div>
                  <span class="text-dark">Rs: <%= product.price %></span>
                </div>
              </div>
            </div>
          </div>
        </div>
      <%end%>
    </div>
  </div>
  </div>
</section>

app/views/home/shared/_blogs.html.erb
<div class="my-lg-14 my-8">
  <div class="container">
    <!-- row -->
    <div class="table-responsive-xxl pb-6 pb-lg-0">
      <div class="row g-4 flex-nowrap">
        <% @blogs.each do |blog| %>
          <div class="col">
            <div class="card border-0 card-hover">
              <a href="<%= blog_path(blog.slug) %>" class="img-zoom">
                <%= image_tag url_for(blog.cover_image), alt: blog.title, class: "rounded w-100 fixed-dimension-img" if blog.cover_image.present? %>
              </a>
              <div class="position-absolute bg-dark-info w-100 bottom-0 py-3 px-4 rounded-bottom">
                <a href="#" class="text-white d-flex align-items-center btn-transition">
                  <%= blog.title %>
                </a>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/shared/_category.html.erb
<section class="my-lg-14 my-8">
  <div class="container">
    <div class="row align-items-center mb-6">
      <div class="col-10">
        <div>
          <!-- heading    -->
          <h3 class="align-items-center d-flex mb-0 h4">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="feather feather-layers text-primary">
              <polygon points="12 2 2 7 12 12 22 7 12 2"></polygon>
              <polyline points="2 17 12 22 22 17"></polyline>
              <polyline points="2 12 12 17 22 12"></polyline>
            </svg>
            <span class="ms-3">Livestock Categories</span>
          </h3>
        </div>
      </div>
      <div class="col-2">
        <div class="slider-arrow slider-8-columns-arrow" id="slider-8-columns-arrows"></div>
      </div>
    </div>
    <div class="row g-6">
      <div class="col-12">
        <div class="position-relative">
          <div class="slider-8-columns ctegories-slider" id="slider-8-columns">
            <!-- item -->
            <% @categories.each do |category| %>
              <div class="item">
                <!-- item -->
                <a href="<%= products_path(category_id: category.id) %>" class="text-decoration-none text-inherit">
                  <!-- card -->
                  <div class="card mb-3 card-lift category-card">
                    <div class="card-body text-center d-flex flex-column">
                      <div class="category-image">
                        <%= image_tag category.image.attached? ? url_for(category.thumbnail) : 'theme/png/no-image.png', alt: category.name %>
                      </div>
                      <div class="category-name"><%= category.name %></div>
                    </div>
                  </div>
                </a>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/shared/_main_slider.html.erb
<section class="mt-3">
  <div class="container">
    <div class="hero-slider">
      <% Slider.active.ordered.each do |slider| %>
        <div style="background: url(<%= url_for(slider.image) || asset_path('banner/b1.jpg') %>) no-repeat; background-size: cover; border-radius: 0.5rem; background-position: center">
          <div class="ps-lg-12 py-lg-16 col-xxl-5 col-lg-7 col-md-8 py-14 px-8 text-xs-center">
            <h1 class="text-dark display-5 fw-bold mt-4"><%= slider.title.html_safe %></h1>
            <p class="lead text-dark"><%= slider.content %></p>
            <% if slider.button_text.present? && slider.button_link.present? %>
              <a href="<%= slider.button_link %>" class="btn btn-dark mt-3">
                <%= slider.button_text %>
              </a>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/home/shared/_popular_products.html.erb
<section class="my-lg-14 my-8">
  <div class="container">
    <!-- row -->
    <div class="row align-items-center mb-6">
      <div class="col-lg-10 col-10">
        <!-- heading -->
        <h3 class="align-items-center d-flex mb-0 h4">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="feather feather-star text-primary">
            <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon>
          </svg>
          <span class="ms-3">Popular Ads</span>
        </h3>
      </div>
      <div class="col-lg-2 col-2">
        <div class="slider-arrow" id="slider-second-arrows"></div>
      </div>
    </div>
    <!-- slider -->
    <div class="product-slider-second" id="slider-second">
      <!-- item -->
      <% @popular_products.each do |product| %>
        <div class="item">
          <!-- item -->
          <div class="card card-product mb-lg-4">
            <div class="card-body">
              <div class="text-center position-relative">

<!--                 <a href="#!"><img src="/assets/theme/products/product-img-18.jpg" alt="Grocery Ecommerce Template" class="mb-3 img-fluid" /></a>-->

                <%= link_to product_path(product) do %>
                  <div class="product-img-container">
                    <% if product.primary_image.attached? %>
                      <%= image_tag url_for(product.watermarked_primary_image), alt: product.short_description %>
                    <% else %>
                      <%= image_tag 'theme/png/no-image.png', alt: product.short_description %>
                    <% end %>
                  </div>
                <% end %>

              </div>
              <!-- title -->
              <div class="text-small mb-1">
                <a href="#!" class="text-decoration-none text-muted"><small><%= product.category_name %></small></a>
              </div>
              <h2 class="fs-6">
                <%= link_to product.name, product_path(product), class: 'text-inherit text-decoration-none' %>
              </h2>
              <div class="text-warning">
                <!-- rating -->
                <small>
                  <i class="bi bi-star-fill"></i>
                  <i class="bi bi-star-fill"></i>
                  <i class="bi bi-star-fill"></i>
                  <i class="bi bi-star-half"></i>
                  <i class="bi bi-star"></i>
                </small>
                <span class="text-muted small">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-eye">
                    <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                    <circle cx="12" cy="12" r="3"></circle>
                  </svg>
                  <%= product.view_count || 0 %>
                </span>
              </div>
              <!-- price -->
              <div class="d-flex justify-content-between align-items-center mt-3">
                <div>
                  <span class="text-dark">Rs: <%= product.price %></span>
                </div>
              </div>
            </div>
          </div>
        </div>
      <%end%>

    </div>
  </div>
</section>

app/views/home/shared/_recent_products.html.erb
<section class="my-lg-14 my-8">
  <div class="container">
    <!-- row -->
    <div class="row align-items-center mb-6">
      <div class="col-lg-10 col-10">
        <!-- heading -->
        <h3 class="align-items-center d-flex mb-0 h4">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="feather feather-star text-primary">
            <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon>
          </svg>
          <span class="ms-3">Recent Ads</span>
        </h3>
      </div>
      <div class="col-lg-2 col-2">
        <div class="slider-arrow" id="slider-fourth-arrows"></div>
      </div>
    </div>
    <!-- slider -->
    <div class="product-slider-second" id="slider-fourth">
      <!-- item -->
      <% @recent_products.each do |product| %>
        <div class="item">
          <!-- item -->
          <div class="card card-product mb-lg-4">
            <div class="card-body">
              <div class="text-center position-relative">
                <!-- badge -->
<!--                <div class="position-absolute top-0 start-0">-->
<!--                  <span class="badge bg-danger">Featured</span>-->
<!--                </div>-->

<!--                 <a href="#!"><img src="/assets/theme/products/product-img-18.jpg" alt="Grocery Ecommerce Template" class="mb-3 img-fluid" /></a>-->

                <%= link_to product_path(product) do %>
                  <div class="product-img-container">
                    <% if product.primary_image.attached? %>
                      <%= image_tag url_for(product.watermarked_primary_image), alt: product.short_description %>
                    <% else %>
                      <%= image_tag 'theme/png/no-image.png', alt: product.short_description %>
                    <% end %>
                  </div>
                <% end %>
              </div>
              <!-- title -->
              <div class="text-small mb-1">
                <a href="#!" class="text-decoration-none text-muted"><small><%= product.category_name %></small></a>
              </div>
              <h2 class="fs-6">
                <%= link_to product.name, product_path(product), class: 'text-inherit text-decoration-none' %>
              </h2>
              <div class="text-warning">
                <!-- rating -->
                <small>
                  <i class="bi bi-star-fill"></i>
                  <i class="bi bi-star-fill"></i>
                  <i class="bi bi-star-fill"></i>
                  <i class="bi bi-star-half"></i>
                  <i class="bi bi-star"></i>
                </small>
                <span class="text-muted small">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-eye">
                    <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                    <circle cx="12" cy="12" r="3"></circle>
                  </svg>
                  <%= product.view_count || 0 %>
                </span>
              </div>
              <!-- price -->
              <div class="d-flex justify-content-between align-items-center mt-3">
                <div>
                  <span class="text-dark">Rs: <%= product.price %></span>
                </div>
              </div>
            </div>
          </div>
        </div>
      <%end%>
    </div>
    </div>
  </div>
</section>

app/views/home/shared/_services.html.erb
<section class="my-lg-14 my-8">
  <div class="container">
    <div class="row align-items-center mb-8">
      <div class="col-md-8 col-12">
        <!-- heading -->
        <div class="d-flex">
          <div class="mt-1">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-journal text-primary" viewBox="0 0 16 16">
              <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z" />
              <path
                d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z" />
            </svg>
          </div>
          <div class="ms-3">
            <h3 class="mb-0">Our Services</h3>
            <p class="mb-0">Check out most our services.</p>
          </div>
          <div></div>
        </div>
      </div>
      <!-- button -->
      <div class="col-md-4 text-end d-none d-md-block">
        <%= link_to "View all services", services_path, class: "btn btn-primary", role: 'button', 'aria-expanded': 'false' %>
      </div>
    </div>
    <!-- slider -->
    <div id="serviceCarousel" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        <% if @published_services.present? %>
          <% @published_services.each_slice(4).with_index do |services, index| %>
            <div class="carousel-item <%= 'active' if index == 0 %>">
              <div class="row">
                <% services.each do |service| %>
                  <%= render partial: "services/service_slider", locals: { service: service } %>
                <% end %>
              </div>
            </div>
          <% end %>
        <% else %>
          <div class="carousel-item active">
            <div class="container">
              <div class="news-list-warp">
                <h1 class="text-align-center mx-auto">
                  No services available!
                </h1>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>